### ISSUE TITLE
the added vanilla bookshelves seem to have black wool as their textures!

### ISSUE THREAD

**Issue by Azutte** [ganymedes01/WoodStuff#2] opened 2015-06-27 04:42 UTC
![2015-06-26_21 39 31](https://cloud.githubusercontent.com/assets/6581284/8390484/2e6590c8-1c4c-11e5-9789-f7f7e36380de.png)

**Comment by buttilda** [comment] 2015-06-28 02:23
What on earth have you done? lol

What mods have you got installed?

**Comment by Azutte** [comment] 2015-06-28 06:06
http://imgur.com/ZzUnZsl

**Comment by buttilda** [comment] 2015-06-28 15:02
I think I know what the problem is :3

**Comment by buttilda** [comment] 2015-06-28 15:03
Do you know how to compile the mod? Would be nice if you could test it (so I don't need to download all of those mods)

**Comment by Azutte** [comment] 2015-06-28 18:12
Wellll.... no, but: 

(link removed)

**Comment by buttilda** [comment] 2015-06-30 02:40
I've released an update that should fix the issue.
Try version 1.0.1 and let me know if it fixes it :)

**Comment by Azutte** [comment] 2015-06-30 10:07
Yes, it did fix it. Did you manage to diagnose the issue? I'm interested in what caused it.

Also: [this](http://pastebin.com/a2k9hAxx) does not seem to have put in any new blocks, what have I done wrong?

**Comment by buttilda** [comment] 2015-06-30 16:18
I'm not sure how much you know of the technical stuff so I'll explain as best as I can assuming you know nothing:
Minecraft loads of the icons for the blocks and stitches them together in a single texture. The blocks then store just the coordinates of their textures on that sheet so they can use them for rendering.
What I was doing was storing the coordinates when the first bookshelf was being created and using that same coordinate for all of them. But what was happening is the stitched texture was changing after I cached the coordinates, so then I'd end up using the coordinates to a different block texture (in your case, black wool). All I had to do is make sure that the caching didn't occur anymore and the problem was fixed :)

As for why you're unable to add blocks, I'm not sure why, what you're doing should be working. Can you send me your logs? There should be an error in there somewhere.

**Comment by buttilda** [comment] 2015-06-30 16:19
I'll close the issue since it was fixed. But feel free to keep commenting on it.

**Closed as completed by buttilda** 2015-06-30 16:19 UTC

**Comment by Azutte** [comment] 2015-07-01 04:04
[http://pastebin.com/NSU5hiRu](http://pastebin.com/NSU5hiRu)

I'm not actually seeing anything about woodstuff in there, should I be retrieving some different kind of log?
