### ISSUE TITLE
[Compatibility] Forestry 4

### ISSUE THREAD

**Issue by mrammy** [ganymedes01/WoodStuff#19] opened 2015-10-18 22:05 UTC
Not all forestry 4 plank's woods are supported. It would be very appreciated if these got added.

**Comment by buttilda** [comment] 2015-10-19 00:43
Which ones are missing?

**Comment by mrammy** [comment] 2015-10-19 00:50
Everything except larch

**Comment by buttilda** [comment] 2015-10-19 00:56
Right...
I'm afraid it's due to the way they do their planks now using TileEntities instead of metadata. I'm not sure how I'll workaround that... WoodStuff was coded assuming that every plank used metadata to define it's icon. I might need to re-write a huge bit of it to make this work D=

**Comment by dirtyfargo** [comment] 2015-11-18 17:51
I think I am getting a similar issue, my launcher is freezing on startup with this error message on 1.3.0:
https://gist.github.com/864f548ae50f0eb1a9b6

**Comment by buttilda** [comment] 2015-11-18 18:14
I'll have a look into what's going on with Forestry's woods. I think they reverted some of the changes.

You can disable Forestry support in the config file to stop that from happening in the mean time

**Comment by dirtyfargo** [comment] 2015-11-18 18:38
Yeah, all my Forestry addons have been having trouble for some time now, I guess its because stuff keeps changing :P I disabled the Forestry module for now, thank ya =)

**Comment by buttilda** [comment] 2015-11-18 18:52
I've sent them a PR to request a small change that would allow WoodStuff to maintain support for Forestry: https://github.com/ForestryMC/ForestryMC/pull/971

If it doesn't get merged (or another workaround isn't put in place) I'll have no other option but to remove support for Forestry )=

**Comment by buttilda** [comment] 2015-11-18 19:49
The workaround was merged onto Forestry. Closing this as the problem is now solved.

I'll release an update shortly that will stop the crashing. But to actually get the woods working you'll need to use the latest Unstable build of Forestry (which might be, well, unstable), so proceed with care :3

**Closed as completed by buttilda** 2015-11-18 19:49 UTC
